### PR TITLE
feat: add attachment management support

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

增加附件管理的功能，适配 https://github.com/halo-dev/halo/pull/2354

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2330

#### Screenshots:

None

#### Special notes for your reviewer:

todo list:

- [x] 根据分组筛选附件列表。
- [x] 非图片文件支持显示占位图。
- [x] 完善选择附件组件。
- [ ] ~~附件引用关系查询。~~

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — APPROVED** [review]
/approve

**Pull request merged**
