### PR TITLE
feat: api supports field filtering

### PR DESCRIPTION
**Pull request by ruibaby**
Signed-off-by: Ryan Wang <i@ryanc.cc>

#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

适配 https://github.com/halo-dev/halo/pull/2279

接口支持通过参数筛选数据。

#### Which issue(s) this PR fixes:

None

#### Screenshots:

None

#### Special notes for your reviewer:

/hold until https://github.com/halo-dev/halo/pull/2279 merge

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
/unhold
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
