### PR TITLE
WIP: perf: 优化附件预览和日志评论弹窗

### PR DESCRIPTION
**Pull request by cetr**

### CODE REVIEW

**Comment by ruibaby** [comment]
你好 @cetr ，请将这两个修改分开 PR 提交，并附上前后对比图。

**Comment by cetr** [comment]
css公用的，没法分开，稍等我附上对比图

**Comment by cetr** [comment]
### 附件预览

before：

https://user-images.githubusercontent.com/49756728/155691918-aa9cd2c7-8779-48f5-84d8-3d5063c9d65d.mp4


https://user-images.githubusercontent.com/49756728/155691937-dd10ccb8-52a7-4b87-bf09-34fc16b65787.mp4

after：

https://user-images.githubusercontent.com/49756728/155691987-fd4ddf17-6195-4863-9a48-1d136675ea42.mp4


https://user-images.githubusercontent.com/49756728/155692001-47093006-0ded-44a7-b309-d60e03c8cd6e.mp4

### 日志评论

before：

https://user-images.githubusercontent.com/49756728/155692069-8035cd09-c7a5-4f11-8ccd-926dacfb570a.mp4


https://user-images.githubusercontent.com/49756728/155692085-a9b86bda-7beb-4b2c-9cb6-3dc2ff53494f.mp4

after：

https://user-images.githubusercontent.com/49756728/155692113-227a7986-b8a4-4ba8-9081-25aaf43eaa0d.mp4


https://user-images.githubusercontent.com/49756728/155692124-19701ea4-0667-447c-9238-64fa5b8d71db.mp4

**Comment by cetr** [comment]
视频可能需要下载到本地才能查看

**Pull request closed without merging**
