### PR TITLE
feat: add support for theme management

### PR DESCRIPTION
**Pull request by ruibaby**
Signed-off-by: Ryan Wang <i@ryanc.cc>

#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

添加基础的主题管理支持，适配 https://github.com/halo-dev/halo/pull/2280

/hold until https://github.com/halo-dev/halo/pull/2280 merge

#### Which issue(s) this PR fixes:

None

#### Screenshots:

|image|image|
| ---- | ---- |
|image|      |

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/retitle feat: add support for theme management

/cc @halo-dev/sig-halo-admin

**Review by JohnNiang — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
