### PR TITLE
feat: single page management

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

自定义（独立）页面的管理功能。适配 https://github.com/halo-dev/halo/pull/2381

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2379

#### Screenshots:

None

#### Special notes for your reviewer:

功能测试流程：

1. 本地仓库 Checkout 到本 PR。
2. 更新依赖：`pnpm install`
3. 构建依赖包：`pnpm build:packages`
4. 下载并在后台安装最新的测试主题：https://github.com/halo-sigs/theme-anatole/actions/runs/3005005732
5. 进入到后台的 `页面 -> 自定义页面`
6. 测试新建页面，以及管理功能。

/hold until https://github.com/halo-dev/halo/pull/2381 merge

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
I got the following issue when I was trying to start it:

```bash
✓ 12 modules transformed.                                                                                                                                                                                 22:34:23

 ERROR  [vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "@halo-dev/components/dist/style.css" from "src/setup/setupStyles.ts".                                                            22:34:23
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`


 ERROR  error during build:                                                                                                                                                                               22:34:23
Error: [vite]: Rollup failed to resolve import "@halo-dev/components/dist/style.css" from "src/setup/setupStyles.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///home/johnniang/workspaces/halo-dev/halo-admin/node_modules/.pnpm/vite@3.0.9_sass@1.54.5/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43721:19)
    at onwarn (file:///home/johnniang/workspaces/halo-dev/halo-admin/node_modules/.pnpm/vite@3.0.9_sass@1.54.5/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:43520:13)
    at Object.onwarn (file:///home/johnniang/workspaces/halo-dev/halo-admin/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/es/shared/rollup.js:23188:13)
    at ModuleLoader.handleResolveId (file:///home/johnniang/workspaces/halo-dev/halo-admin/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/es/shared/rollup.js:22379:26)
    at file:///home/johnniang/workspaces/halo-dev/halo-admin/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/es/shared/rollup.js:22340:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 ELIFECYCLE  Command failed with exit code 1.
```

The commands I executed were:

```bash
pnmp i
cd packages/shared
pnpm build
cd ../../
pnpm build
# Issue occurred
```

Am I missing something? Please feel free to correct  me.

**Comment by ruibaby** [comment]
@JohnNiang Try:

```
pnpm install 

pnpm build:packages

pnpm dev
```

@halo-dev/api-client has been published to npm

**Comment by JohnNiang** [comment]
After publishing a SinglePage, I got the following error in server:

```java
2022-09-07T23:21:30.631+08:00 ERROR 16120 --- [undedElastic-16] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-16] Exception processing template "page": Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:na]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-09-07T23:21:30.631+08:00 ERROR 16120 --- [undedElastic-16] r.h.a.t.e.SpringWebFluxTemplateEngine    : [THYMELEAF][boundedElastic-16] Exception processing template "page": Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:na]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-09-07T23:21:30.644+08:00 ERROR 16120 --- [undedElastic-16] a.w.r.e.AbstractErrorWebExceptionHandler : [389fdae4-475]  500 Server Error for HTTP GET "/hello"

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:201)
	run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:182)
Error has been observed at the following site(s):
	*_____________Mono.create ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:182)
	|_               Mono.log ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:235)
	|_       Mono.subscribeOn ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:236)
	|_       Mono.subscribeOn ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.processStream(SpringWebFluxTemplateEngine.java:163)
	|_           Mono.flatMap ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeWith(AbstractServerHttpResponse.java:185)
	|_         Mono.doOnError ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeWith(AbstractServerHttpResponse.java:206)
	|_       Mono.doOnDiscard ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeWith(AbstractServerHttpResponse.java:207)
	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.result.view.AbstractView.render(AbstractView.java:203)
	|_       Mono.subscribeOn ⇢ at run.halo.app.theme.HaloViewResolver$HaloView.lambda$render$0(HaloViewResolver.java:52)
	*____________Mono.flatMap ⇢ at run.halo.app.theme.HaloViewResolver$HaloView.render(HaloViewResolver.java:48)
	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.function.server.DefaultRenderingResponseBuilder$DefaultRenderingResponse.writeToInternal(DefaultRenderingResponseBuilder.java:196)
	|_             checkpoint ⇢ Handler run.halo.app.theme.router.strategy.SinglePageRouteStrategy$$Lambda$1784/0x000000080155bc70@af5e9e5 [DispatcherHandler]
	|_     Mono.onErrorResume ⇢ at org.springframework.web.reactive.DispatcherHandler.handleResult(DispatcherHandler.java:181)
	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.DispatcherHandler.lambda$handleResult$5(DispatcherHandler.java:182)
	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:154)
	*______________Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
	*_______________Mono.then ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:52)
	*______Mono.switchIfEmpty ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:52)
	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:53)
	|_               Mono.map ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:54)
	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:55)
	|_             checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*______________Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
	|_          Mono.doOnEach ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:87)
	|_        Mono.doOnCancel ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:88)
	*__Mono.transformDeferred ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:82)
	|_             checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*______________Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
	|_     Mono.onErrorResume ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
	*______________Mono.error ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler$CheckpointInsertingHandler.handle(ExceptionHandlingWebHandler.java:98)
	|_             checkpoint ⇢ HTTP GET "/hello" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
		at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
		at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:na]
		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
		at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

@guqing Please help us confirm it.

**Comment by guqing** [comment]
> After publishing a SinglePage, I got the following error in server:
> 
> ```java
> 2022-09-07T23:21:30.631+08:00 ERROR 16120 --- [undedElastic-16] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-16] Exception processing template "page": Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
> 
> org.thymeleaf.exceptions.TemplateInputException: Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
> 	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:na]
> 	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
> 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
> 
> 2022-09-07T23:21:30.631+08:00 ERROR 16120 --- [undedElastic-16] r.h.a.t.e.SpringWebFluxTemplateEngine    : [THYMELEAF][boundedElastic-16] Exception processing template "page": Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
> 
> org.thymeleaf.exceptions.TemplateInputException: Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
> 	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:na]
> 	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
> 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
> 
> 2022-09-07T23:21:30.644+08:00 ERROR 16120 --- [undedElastic-16] a.w.r.e.AbstractErrorWebExceptionHandler : [389fdae4-475]  500 Server Error for HTTP GET "/hello"
> 
> org.thymeleaf.exceptions.TemplateInputException: Error resolving template [page], template might not exist or might not be accessible by any of the configured Template Resolvers
> 	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Assembly trace from producer [reactor.core.publisher.MonoCreate] :
> 	reactor.core.publisher.Mono.create(Mono.java:201)
> 	run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:182)
> Error has been observed at the following site(s):
> 	*_____________Mono.create ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:182)
> 	|_               Mono.log ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:235)
> 	|_       Mono.subscribeOn ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.createFullStream(SpringWebFluxTemplateEngine.java:236)
> 	|_       Mono.subscribeOn ⇢ at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.processStream(SpringWebFluxTemplateEngine.java:163)
> 	|_           Mono.flatMap ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeWith(AbstractServerHttpResponse.java:185)
> 	|_         Mono.doOnError ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeWith(AbstractServerHttpResponse.java:206)
> 	|_       Mono.doOnDiscard ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeWith(AbstractServerHttpResponse.java:207)
> 	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.result.view.AbstractView.render(AbstractView.java:203)
> 	|_       Mono.subscribeOn ⇢ at run.halo.app.theme.HaloViewResolver$HaloView.lambda$render$0(HaloViewResolver.java:52)
> 	*____________Mono.flatMap ⇢ at run.halo.app.theme.HaloViewResolver$HaloView.render(HaloViewResolver.java:48)
> 	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.function.server.DefaultRenderingResponseBuilder$DefaultRenderingResponse.writeToInternal(DefaultRenderingResponseBuilder.java:196)
> 	|_             checkpoint ⇢ Handler run.halo.app.theme.router.strategy.SinglePageRouteStrategy$$Lambda$1784/0x000000080155bc70@af5e9e5 [DispatcherHandler]
> 	|_     Mono.onErrorResume ⇢ at org.springframework.web.reactive.DispatcherHandler.handleResult(DispatcherHandler.java:181)
> 	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.DispatcherHandler.lambda$handleResult$5(DispatcherHandler.java:182)
> 	*____________Mono.flatMap ⇢ at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:154)
> 	*______________Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
> 	*_______________Mono.then ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:52)
> 	*______Mono.switchIfEmpty ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:52)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:53)
> 	|_               Mono.map ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:54)
> 	|_           Mono.flatMap ⇢ at org.springframework.security.web.server.WebFilterChainProxy.filter(WebFilterChainProxy.java:55)
> 	|_             checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
> 	*______________Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
> 	|_          Mono.doOnEach ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:87)
> 	|_        Mono.doOnCancel ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:88)
> 	*__Mono.transformDeferred ⇢ at org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter.filter(MetricsWebFilter.java:82)
> 	|_             checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
> 	*______________Mono.defer ⇢ at org.springframework.web.server.handler.DefaultWebFilterChain.filter(DefaultWebFilterChain.java:106)
> 	|_     Mono.onErrorResume ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler.handle(ExceptionHandlingWebHandler.java:77)
> 	*______________Mono.error ⇢ at org.springframework.web.server.handler.ExceptionHandlingWebHandler$CheckpointInsertingHandler.handle(ExceptionHandlingWebHandler.java:98)
> 	|_             checkpoint ⇢ HTTP GET "/hello" [ExceptionHandlingWebHandler]
> Original Stack Trace:
> 		at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 		at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.M2.jar:3.1.0.M2]
> 		at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:na]
> 		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 		at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
> 		at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
> 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
> 		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
> 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
> 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
> 		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
> ```
> 
> @guqing Please help us confirm it.

主体端需要一个 page.html 的模板才可以渲染

**Review by JohnNiang — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
