### PR TITLE
feat: menus management

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

增加导航菜单的支持。适配 https://github.com/halo-dev/halo/pull/2303

/hold until https://github.com/halo-dev/halo/pull/2303 merge

#### Which issue(s) this PR fixes:

None

#### Screenshots:

None

#### Special notes for your reviewer:

Checklist:

- [ ] ~~支持关联类型（文章、分类等）的菜单项~~
- [x] 完善单元测试
- [x] 更新 `@halo-dev/api-client` 包

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
/approve

**Review by guqing — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
当前因为 Vercel 无法正常构建 halo-admin-ui，所以无法自动合并。我将手动合并此 PR。

**Pull request merged**
