### PR TITLE
refactor: remove encodeURI handling of attachment paths.

### PR DESCRIPTION
**Pull request by FanZeros**
https://github.com/halo-dev/halo/pull/1874 后端对链接进行encodeURI，前端去除
避免特殊字符的错误

```release-note
None
```

fixes halo-dev/halo#1899 
fixes halo-dev/halo#1918

### CODE REVIEW

**Comment by ruibaby** [comment]
/hold
/milestone 1.5.x
/kind bug

等待 https://github.com/halo-dev/halo/pull/1874 合并。

**Comment by ruibaby** [comment]
/retitle refactor: disable encodeURI handling of attachment paths.

**Review by JohnNiang — APPROVED** [review]
It works very well.

Thank @FanZeros for contribution!

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Pull request merged**
