### PR TITLE
feat: menu items support setting ref relations

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

菜单项支持设置与文章、分类、标签的关联关系。关联之后，当被关联对象有所改变时，同步菜单项更新。适配：https://github.com/halo-dev/halo/pull/2380

> 自定义页面（pageRef）会等到 https://github.com/halo-dev/halo/pull/2381 合并之后再做适配。

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2295

#### Screenshots:

image
image

#### Special notes for your reviewer:

/hold until https://github.com/halo-dev/halo/pull/2380 merge

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by JohnNiang — COMMENTED** [review]
/lgtm
It works very well.

**Comment by ruibaby** [comment]
/retitle feat: menu items support setting ref relations

**Review by guqing — COMMENTED** [review]
/approve

**Review by JohnNiang — APPROVED** [review]
/lgtm

**Pull request merged**
