### PR TITLE
Add build-push job for Halo admin

### PR DESCRIPTION
**Pull request by JohnNiang**
#### What type of PR is this?

/kind feature
/milestone 2.0

#### What this PR does / why we need it:

Add build-push job for admin project. This job will produce docker image `ghcr.io/halo-dev/admin-dev`.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by JohnNiang** [comment]
/unhold
All checks pass.

**Pull request merged**
