### PR TITLE
fix: clear the verification result when editing the category directory.

### PR DESCRIPTION
**Pull request by Yorksh1re**
before:
before

after:
after

### CODE REVIEW

**Review by JohnNiang — APPROVED** [review]
Thanks for your first contribution!

LGTM

**Comment by Yorksh1re** [comment]
啊，图太慢了，问题和效果可以看这里：
before: https://cdn.blog.athesoft.com/halo/before_1646897548095.gif
after: https://cdn.blog.athesoft.com/halo/after_1646897544786.gif

**Review by ruibaby — APPROVED** [review]
LGTM

**Review by guqing — APPROVED** [review]

**Comment by ruibaby** [comment]
@Yorksh1re Hi，是否可以再看看其他地方需不需要改呢？

**Comment by Yorksh1re** [comment]
好的，我看下哈~

**Comment by ruibaby** [comment]
> 好的，我看下哈~

期待下次贡献。😀

**Pull request merged**
