### PR TITLE
perf: under the list, after deleting all the data on the current page, query the data on the previous page

### LINKED ISSUE #472: 删除文章导致无法分页
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

H2

### 在线站点地址

www.xiaoyx.club

### 发生了什么？

当在后台，文章➡所有文章中，如果存在多页文章，那么把一页的所有文章删除完毕，并不会自动跳转到上一页，并且点击左上角的文章时，也不会进行跳转，只能刷新网页或者跳转到后台首页

### 相关日志输出

_No response_

### 附加信息

图片

图片

### PR DESCRIPTION
**Pull request by QuentinHsu**
fix #472 
/cc @halo-dev/sig-halo-admin

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by ruibaby — COMMENTED** [review]
/approve

**Review by ruibaby — APPROVED** [review]

**Review by guqing — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
