### PR TITLE
fix: ui issue caused by too long parent category selection list in new category

### PR DESCRIPTION
**Pull request by SladeGranger**
#### What type of PR is this?

/kind bug

#### What does this PR do?

在上级目录分类过多时添加滚动条,以解决无法选中部分分类的问题。

#### Which issue does this PR fix?

fixed https://github.com/halo-dev/halo/issues/1920

#### Screenshot

issue_1920

#### Does this PR introduce a user-facing change?

```release-notes
修复新建分类中父级分类选择列表过长导致的 UI 问题
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
/retitle fix: ui issue caused by too long parent category selection list in new category

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
