### PR TITLE
chore: add pull request template

### PR DESCRIPTION
**Pull request by ruibaby**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

规范 Pull Request 的提交，以及支持生成 Release Notes。

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo-admin

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by ruibaby** [comment]
/hold 

pnpm-lock.yaml 似乎被修改。

**Comment by ruibaby** [comment]
> /hold
> 
> pnpm-lock.yaml 似乎被修改。

/unhold

**Review by JohnNiang — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/approve

**Pull request merged**
