### PR TITLE
feat: add buttons that update journal type directly

### PR DESCRIPTION
**Pull request by zjy4fun**
#### What type of PR is this?
/kind feature
/area admin

#### What this PR does / why we need it:

优化日志列表设置公开/隐藏状态的方式

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/2301

#### Screenshots:
journal-type

#### Does this PR introduce a user-facing change?

```release-note
优化日志列表设置公开/隐藏状态的方式
```

### CODE REVIEW

**Comment by JohnNiang** [comment]
/milestone 1.6.x

Hi @manction，可以帮忙手动测试一下么 : P

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Comment by ruibaby** [comment]
/retitle feat: add buttons that update journal type directly

**Review by JohnNiang — APPROVED** [review]
/approve
/milestone 1.6.x

**Review by guqing — COMMENTED** [review]
/lgtm

**Pull request merged**
