### PR TITLE
fix: the mode.topPriority involving computed is not initialized

### LINKED ISSUE #523: 首次创建文章时是否置顶按钮属性绑定问题导致switch无法切换
### What is version of Halo has the issue?

1.5.0

### What database are you using?

H2

### Your site address.

_No response_

### What happened?

浮现步骤：
1. 点击菜单 `文章/写文章`
2. 随意输入后点发布，如下界面
image
3. 点击是否置顶的switch没有反应

/kind bug
/assign @QuentinHsu

### PR DESCRIPTION
**Pull request by QuentinHsu**
fix #523 
/cc @halo-dev/sig-halo-admin

### CODE REVIEW

**Review by guqing — APPROVED** [review]
/approve

**Review by ruibaby — APPROVED** [review]
/lgtm /approve

**Pull request merged**
