### PR TITLE
Replace zh-cmn-Hans with cmn-Hans

### PR DESCRIPTION
**Pull request by wordlesswind**
#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:
zh-cmn-Hans is marked as deprecated.
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

#### Which issue(s) this PR fixes:

NONE

#### Special notes for your reviewer:
For compatibility, `zh-Hans` or `zh-Hans-CN` are better choices, they are not deprecated.

#### Does this PR introduce a user-facing change?

```release-note
Replace zh-cmn-Hans with cmn-Hans
```

### CODE REVIEW

**Review by ruibaby — COMMENTED** [review]
/lgtm

**Review by guqing — COMMENTED** [review]
/lgtm

**Review by JohnNiang — COMMENTED** [review]
/lgtm

**Comment by guqing** [comment]
Congrats on merging your first pull request! 🎉🎉🎉

**Pull request merged**
